#!/usr/bin/env python3

import os
charm_dir = os.path.dirname(os.path.abspath(os.path.join(__file__, "..")))
os.environ['CHARM_DIR'] = charm_dir

# Load modules from $CHARM_DIR/lib
import sys
sys.path.append(os.path.join(charm_dir, 'lib'))

from charmhelpers.core.unitdata import kv
from charms.reactive import set_state
from charms.metering import CODE, INFO


if __name__ == '__main__':
    unit_data = kv()
    current = os.environ['JUJU_METER_STATUS']
    if current:
        current = str(current).lower()
        unit_data.set(CODE, current)
        unit_data.set(INFO, os.environ.get('JUJU_METER_INFO'))
        set_state('meter.status.changed')
        set_state('meter.status.%s' % (current))
    unit_data.flush(True)
    unit_data.close()
